### PR TITLE
commit for making power enum work with rails 5

### PR DESCRIPTION
**Pull request by eugenefilimonov**
This adds compatibility with rails 5 from our [citybase common](https://github.com/Pay-Ease/citybase_common/pull/12) gem upgrade.

### CODE REVIEW

**Comment by powder** [comment]
LGTM

**Comment by mikenichols** [comment]
LGTM 👍

**Comment by kmwhite** [comment]
LGTM.

**Comment by MityaLiu** [comment]
We should make a PR into original repository or rename this into Power Hrenum.

**Comment by mikenichols** [comment]
Did we want to bump the version number as well?

**Pull request merged**
